"""
Drone IDS - Base Detector Class
Abstract base class for all detectors.
"""
import time
import logging
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, List
from dataclasses import dataclass, field
from enum import Enum

from ..core.message_bus import message_bus, Message, MessageType
from ..core.ids_engine import engine
from ..core.config import config


class AlertSeverity(Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


@dataclass
class Alert:
    """Security alert generated by detectors."""
    detector_name: str
    alert_type: str
    severity: AlertSeverity
    timestamp: float = field(default_factory=time.time)
    description: str = ""
    details: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    raw_data: Dict[str, Any] = field(default_factory=dict)
    mitre_attack: str = ""
    evidence_hash: str = ""


class BaseDetector(ABC):
    """Abstract base class for all detectors."""
    
    def __init__(self, name: str = None):
        self.name = name or self.__class__.__name__
        self.logger = logging.getLogger(f'drone_ids.detector.{self.name}')
        self.logger.setLevel(logging.INFO)
        self._engine = None
        self._enabled = True
        self._initialized = False
        self._last_alert_time: Dict[str, float] = {}
        self.alert_cooldown = config.get('engine.alert_cooldown', 1.0)
    
    def set_engine(self, engine_instance) -> None:
        """Set reference to main engine."""
        self._engine = engine_instance
    
    @property
    def engine(self):
        return self._engine
    
    @property
    def enabled(self) -> bool:
        return self._enabled
    
    def enable(self) -> None:
        self._enabled = True
    
    def disable(self) -> None:
        self._enabled = False
    
    @abstractmethod
    def initialize(self) -> None:
        """Initialize detector - called on engine start."""
        pass
    
    @abstractmethod
    def shutdown(self) -> None:
        """Shutdown detector - called on engine stop."""
        pass
    
    @abstractmethod
    def update(self) -> None:
        """Periodic update - called from engine main loop."""
        pass
    
    def on_mavlink_message(self, message: Dict[str, Any]) -> None:
        """Handle MAVLink message - override in subclasses."""
        pass
    
    def on_command(self, command: Dict[str, Any]) -> None:
        """Handle command message - override in subclasses."""
        pass
    
    def on_telemetry(self, telemetry: Dict[str, Any]) -> None:
        """Handle telemetry message - override in subclasses."""
        pass
    
    def generate_alert(self, alert: Alert) -> None:
        """Generate and publish an alert."""
        if not self._should_alert(alert.alert_type):
            return
        
        # Add timestamp if not set
        if alert.timestamp == 0:
            alert.timestamp = time.time()
        
        # Record in engine stats
        if self._engine:
            self._engine.record_alert(alert.alert_type)
        
        # Publish to message bus
        message_bus.publish(Message(
            type=MessageType.ALERT,
            source=self.name,
            data={
                'detector': self.name,
                'alert_type': alert.alert_type,
                'severity': alert.severity.value,
                'timestamp': alert.timestamp,
                'description': alert.description,
                'details': alert.details,
                'confidence': alert.confidence,
                'mitre_attack': alert.mitre_attack,
                'evidence_hash': alert.evidence_hash
            }
        ))
        
        self.logger.warning(f"ALERT [{alert.severity.value}] {alert.alert_type}: {alert.description}")
    
    def _should_alert(self, alert_type: str) -> bool:
        """Check if enough time has passed since last alert of this type."""
        now = time.time()
        last_time = self._last_alert_time.get(alert_type, 0)
        if now - last_time >= self.alert_cooldown:
            self._last_alert_time[alert_type] = now
            return True
        return False
    
    def get_config(self, key: str, default: Any = None) -> Any:
        """Get detector-specific configuration."""
        return config.get(f'{self.name.lower()}.{key}', default)